08:32:00 PM:DEBUG [logger_base.py:15] Mensaje a nivel debug
08:32:00 PM:INFO [logger_base.py:16] Mensaje a nivel info
08:32:00 PM:WARNING [logger_base.py:17] Mensaje a nivel warning
08:32:00 PM:ERROR [logger_base.py:18] Mensaje a nivel error
08:32:00 PM:CRITICAL [logger_base.py:19] Mensaje a nivel critical
11:02:12 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
11:04:44 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
11:06:48 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
11:06:48 PM:DEBUG [Persona.py:55] 
            Id Persona: Jose,
            Nombre: Lepez,
            Apellido: ljose@mail.com,
            Email: None
        
11:09:20 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
11:09:20 PM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@mail.com
        
11:12:11 PM:DEBUG [Persona.py:53] 
            Id Persona: 1,
            Nombre: Juan,
            Apellido: Perez,
            Email: jperez@mail.com
        
11:12:11 PM:DEBUG [Persona.py:55] 
            Id Persona: None,
            Nombre: Jose,
            Apellido: Lepez,
            Email: ljose@mail.com
        
11:12:11 PM:DEBUG [Persona.py:57] 
            Id Persona: 1,
            Nombre: None,
            Apellido: None,
            Email: None
        
12:32:54 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x00000275D5B92790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:36:57 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001ED35312790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:36:57 AM:ERROR [conexion.py:41] Ocurrio un error: type object 'Conexion' has no attribute 'obtenerConexion'
12:48:44 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001F4E0842790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:48:44 AM:ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
12:49:14 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001DEDCEA2790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:49:14 AM:ERROR [conexion.py:41] Ocurrio un error: 'NoneType' object has no attribute 'cursor'
12:50:00 AM:DEBUG [conexion.py:25] Conexion Exitosa: <connection object at 0x000001EDC3052790; dsn: 'user=postgres password=xxx dbname=test_bd host=127.0.0.1 port=5432', closed: 0>
12:50:00 AM:DEBUG [conexion.py:38] Se abrio correctamente el cursor: <cursor object at 0x000001EDC519B680; closed: 0>
